name: Python CI - Practica TDD

on:
  push:
    branch: [ main ]

jobs:
  build::
    runs-on: ubuntu-latest

    steps:

      - name: Clonar repo
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Instala dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ejecuta las pruebas con Pytest
        run: pytest --cov=.